trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Instalar Node.js'

  - script: |
      npm ci
      npx playwright install --with-deps
    displayName: 'Instalar dependencias y Playwright'

  - script: |
      npx playwright test
    displayName: 'Ejecutar pruebas Playwright'

  - task: PublishTestResults@2
    displayName: 'Publicar resultados de pruebas'
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results/junit-results.xml'
      failTaskOnFailedTests: true

  - task: Docker@2
    displayName: 'Construir imagen Docker'
    inputs:
      command: 'build'
      repository: 'legs30011/test-playwright'
      dockerfile: 'Dockerfile'
      containerRegistry: 'docker-hub-legs30011'
      tags: 'latest'

  - task: Docker@2
    displayName: 'Subir imagen Docker a Docker Hub'
    inputs:
      command: 'push'
      repository: 'legs30011/test-playwright'
      containerRegistry: 'docker-hub-legs30011'
      tags: 'latest'