import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://computracedevweb.thermon.com/');
  await page.getByRole('button', { name: 'LOGIN' }).click();
  await page.getByRole('textbox', { name: 'Enter your email, phone, or' }).click();
  await page.getByRole('textbox', { name: 'Enter your email, phone, or' }).fill('svc-cptautomation@thermon.onmicrosoft.com');
  await page.getByRole('textbox', { name: 'Enter your email, phone, or' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Enter the password for svc-' }).fill('Cacho1029');
  await page.getByRole('textbox', { name: 'Enter the password for svc-' }).click();
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'No' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByText('dashboard3').click();
  await page.getByRole('button', { name: 'dashboard' }).click();
  await page.getByLabel('Create project').getByRole('button').click();
  await page.getByText('Create Project1Project').click();
  await page.locator('input[name="projectName"]').click();
  await page.locator('input[name="projectName"]').fill('asdas');
  await page.locator('input[name="projectNumber"]').click();
  await page.locator('input[name="projectNumber"]').fill('213');
  await page.getByRole('textbox', { name: 'MM/DD/YYYY' }).first().click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Finish' }).click();
  await page.getByLabel('Create Circuit').getByRole('button').click();
  await page.getByRole('tab', { name: 'Ref. Dwg.' }).click();
  await page.getByLabel('Add').getByRole('button').click();
  await page.getByRole('combobox', { name: 'Import Reference Drawing Type' }).click();
  await page.getByRole('option', { name: 'Reference' }).click();
  await page.getByRole('textbox', { name: 'Number' }).click();
  await page.getByRole('textbox', { name: 'Number' }).fill('12');
  await page.getByRole('textbox', { name: 'Received' }).click();
  await page.getByRole('textbox', { name: 'Received' }).fill('12/12/5');
  await page.getByRole('textbox', { name: 'Revision' }).click();
  await page.getByRole('textbox', { name: 'Revision' }).fill('wendy');
  await page.getByTestId('confirmHandler').click();
  await page.getByRole('tab', { name: 'Equip. Coord.' }).click();
  await page.getByLabel('Add').getByRole('button').click();
  await page.getByRole('combobox', { name: 'Equipment Coordinates Type ​' }).click();
  await page.getByRole('option', { name: 'Power', exact: true }).click();
  await page.getByRole('textbox', { name: 'Heater Number' }).click();
  await page.getByRole('textbox', { name: 'Heater Number' }).fill('2');
  await page.getByRole('textbox', { name: 'East' }).click();
  await page.getByRole('textbox', { name: 'East' }).fill('4524');
  await page.getByRole('textbox', { name: 'North' }).click();
  await page.getByRole('textbox', { name: 'North' }).fill('524');
  await page.getByRole('textbox', { name: 'Elevation' }).click();
  await page.getByRole('textbox', { name: 'Elevation' }).fill('52');
  await page.getByRole('textbox', { name: 'Tag' }).click();
  await page.getByRole('textbox', { name: 'Tag' }).fill('latest');
  await page.getByTestId('confirmHandler').click();
  await page.getByLabel('Save').getByRole('button').click();
  await page.getByRole('button', { name: 'dashboard' }).click();
  await page.getByRole('button', { name: 'Projects in Cache' }).click();
  await page.getByRole('menuitem', { name: 'test-5266 Are you sure to' }).getByLabel('Are you sure to discard the').click();
  await page.getByRole('button', { name: 'asdas' }).click();
  await page.getByText('Open Project').click();
  await page.getByRole('tab', { name: 'Ref. Dwg.' }).click();
  await page.getByRole('tab', { name: 'Equip. Coord.' }).click();
  await page.getByRole('gridcell', { name: 'Power' }).click();
  await page.getByRole('gridcell', { name: '2', exact: true }).click();
  await page.getByRole('gridcell', { name: '4524' }).click();
  await page.getByRole('gridcell', { name: '4524' }).click();
  await page.getByRole('gridcell', { name: '52', exact: true }).click();
  await page.getByRole('tab', { name: 'Ref. Dwg.' }).click();
  await page.getByRole('gridcell', { name: 'Reference' }).click();
  await page.getByRole('gridcell', { name: '/31/1969' }).click();
});